(function(){
'use strict';
const {Hearth,TECH,BUILD,JOBS,RESOURCE,HOME,distance}=HearthGame;
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d'),KEY='singularity-clicker.hearth.v1',ARCHIVE=KEY+'.completed';
// A native host can supply these three asynchronous methods without changing the simulation.
const platform=window.SingularityPlatform||{load:async key=>localStorage.getItem(key),save:async(key,value)=>localStorage.setItem(key,value),download:async(name,text)=>{const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}};
let game=new Hearth(),selected=new Set([0]),tab='work',map=false,paused=false,saveBlocked=false,loaded=false,buildMode=null,protectMode=false,moveId=null,modalPause=false,practice=null,last=performance.now(),acc=0,saveTime=0,uiTime=0,lastSerialized=null,pointers=new Map(),drag=null,zoom=1,pan={x:0,y:0},w=800,h=500,sx=20,sy=10,origin={x:400,y:20},mapPoints=[],lastComplete=false,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.floor(n).toLocaleString(),clock=n=>Math.floor(n/60)+'m '+Math.floor(n%60)+'s';
function say(text){$('journal').textContent=text;}
async function save(){if(!loaded||saveBlocked)return;try{const text=game.serialize();lastSerialized=text;await platform.save(KEY,text);}catch(e){saveBlocked=true;say('Saving is unavailable. Export your journey before closing.');}}
async function load(){try{const data=await platform.load(KEY);if(data)game=new Hearth(JSON.parse(data));lastSerialized=data;}catch(e){saveBlocked=true;paused=true;say('The existing save could not be opened. Export it or import a backup from Journey.');}loaded=true;lastComplete=game.s.complete;renderUI();}
function modal(kicker,title,body){practice=null;modalPause=true;$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-body').innerHTML=body;if(!$('modal').open)$('modal').showModal();}
function close(){practice=null;$('modal').close();modalPause=false;last=performance.now();}
$('close-modal').onclick=close;$('modal').addEventListener('cancel',()=>{practice=null;modalPause=false;last=performance.now();});
function resize(){const rect=canvas.getBoundingClientRect();w=rect.width;h=rect.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);}
new ResizeObserver(resize).observe(canvas);
function coordinates(){const u=Math.min(w/56,h/31)*zoom;sx=u*1.45;sy=u*.72;origin={x:w*.5+pan.x,y:h*.19+pan.y};}
function iso(x,y,z=0){return{x:origin.x+(x-y)*sx,y:origin.y+(x+y)*sy-z};}
function cell(p){return{x:Math.round(((p.x-origin.x)/sx+(p.y-origin.y)/sy)/2),y:Math.round(((p.y-origin.y)/sy-(p.x-origin.x)/sx)/2)};}
function polygon(points,fill,stroke,width=1){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function line(points,color,width=1){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.stroke();}
function ellipse(x,y,rx,ry,color){ctx.beginPath();ctx.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();}
function diamond(x,y,color,stroke){polygon([iso(x-.5,y-.5),iso(x+.5,y-.5),iso(x+.5,y+.5),iso(x-.5,y+.5)],color,stroke);}
function tree(p,n){const scale=sx/20,height=(15+n.age*32)*scale;ellipse(p.x+5*scale,p.y+3*scale,13*scale,5*scale,'#12271b3a');line([{x:p.x,y:p.y},{x:p.x,y:p.y-height*.72}],'#695344',4*scale);line([{x:p.x,y:p.y-height*.38},{x:p.x+7*scale,y:p.y-height*.65}],'#695344',2*scale);const color=n.protected?'#78955a':n.age<.5?'#718a4e':'#3e6644';for(let j=0;j<3;j++){const yy=p.y-height+j*height*.20,spread=(8+j*4)*scale*(.5+n.age*.5);polygon([{x:p.x,y:yy-8*scale},{x:p.x+spread,y:yy+height*.34},{x:p.x+2*scale,y:yy+height*.3},{x:p.x-spread,y:yy+height*.34}],j===0?'#6a8754':color,'#203d2b55');}if(n.protected){ellipse(p.x,p.y+3,3*scale,2*scale,'#e5c782');}}
function rock(p,scale=1,alpha=1){ctx.globalAlpha=alpha;polygon([{x:p.x-10*scale,y:p.y},{x:p.x-7*scale,y:p.y-9*scale},{x:p.x+3*scale,y:p.y-13*scale},{x:p.x+11*scale,y:p.y-5*scale},{x:p.x+8*scale,y:p.y+3*scale}], '#8f9787','#535f54');polygon([{x:p.x-7*scale,y:p.y-9*scale},{x:p.x+3*scale,y:p.y-13*scale},{x:p.x+2*scale,y:p.y-4*scale},{x:p.x-10*scale,y:p.y}], '#b2b4a0');ctx.globalAlpha=1;}
function flame(p,time,small=false){const scale=sx/20,sz=(small?5:14)*scale;ellipse(p.x,p.y,18*scale,7*scale,'#3d3e2c');for(let i=0;i<7;i++){const a=i/7*Math.PI*2;rock({x:p.x+Math.cos(a)*14*scale,y:p.y+Math.sin(a)*5*scale},.3*scale);}line([{x:p.x-9*scale,y:p.y},{x:p.x+8*scale,y:p.y+2*scale}],'#866046',4*scale);const wave=reduced?0:Math.sin(time*3)*2*scale;polygon([{x:p.x-sz*.6,y:p.y},{x:p.x-sz*.3,y:p.y-sz*.8},{x:p.x+wave,y:p.y-sz*1.7},{x:p.x+sz*.4,y:p.y-sz*.7},{x:p.x+sz*.6,y:p.y}], '#d88142');polygon([{x:p.x-sz*.25,y:p.y},{x:p.x+wave*.3,y:p.y-sz},{x:p.x+sz*.25,y:p.y}], '#ffde8d');if(!reduced)for(let j=0;j<4;j++){const tt=(time*.2+j*.25)%1;ellipse(p.x+Math.sin(tt*5+j)*7*scale,p.y-25*scale-tt*45*scale,4*scale+tt*5*scale,7*scale+tt*5*scale,'rgba(220,218,188,'+(.12*(1-tt))+')');}}
function woodpile(p,amount){const rows=Math.min(5,Math.ceil(amount/12)),scale=sx/20;for(let j=0;j<rows;j++)for(let i=0;i<4-j*.4;i++){const x=p.x+i*5*scale-j*2*scale,y=p.y-j*4*scale;line([{x:x-10*scale,y:y-5*scale},{x,y}],'#7c583c',5*scale);ellipse(x,y,2.3*scale,2*scale,'#c49b65');}}
function basket(p,amount,color='#c39761'){const scale=sx/20;polygon([{x:p.x-8*scale,y:p.y-7*scale},{x:p.x+8*scale,y:p.y-7*scale},{x:p.x+6*scale,y:p.y+3*scale},{x:p.x-6*scale,y:p.y+3*scale}],color,'#6d5938');ellipse(p.x,p.y-7*scale,8*scale,3*scale,'#3f4227');if(amount>0)for(let i=0;i<Math.min(8,Math.ceil(amount/8));i++)ellipse(p.x+(i%3-1)*4*scale,p.y-7*scale-Math.floor(i/3)*3*scale,2.5*scale,2*scale,'#d7b979');}
const hatColor=job=>({wood:'#72964c',farm:'#dabb71',stone:'#e6e0c9',build:'#b58962',food:'#9c7180',water:'#78a3a3',fiber:'#c3ae84',herd:'#c18a55',plow:'#dabb71',idle:'#92785d'}[job]);
function villager(p,time){const at=iso(p.x,p.y),k=sx/20,walking=p.phase==='home'||p.phase==='seek',swing=reduced?0:Math.sin(time*(walking?5:3)+p.id)*2*k,sel=selected.has(p.id);if(sel){ellipse(at.x,at.y+1,10*k,4*k,'#c6dca94f');ctx.strokeStyle='#d5e6a2';ctx.lineWidth=1.5;ctx.beginPath();ctx.ellipse(at.x,at.y+1,10*k,4*k,0,0,Math.PI*2);ctx.stroke();}else ellipse(at.x,at.y+1,7*k,3*k,'#11231b4d');
 const sitting=p.job==='idle',up=sitting?5*k:0;line([{x:at.x-3*k,y:at.y-7*k+up},{x:at.x-4*k+swing,y:at.y}],'#473c2f',3*k);line([{x:at.x+3*k,y:at.y-7*k+up},{x:at.x+4*k-swing,y:at.y}],'#473c2f',3*k);
 polygon([{x:at.x-5*k,y:at.y-17*k+up},{x:at.x+5*k,y:at.y-17*k+up},{x:at.x+6*k,y:at.y-6*k+up},{x:at.x-6*k,y:at.y-6*k+up}],['#b39b74','#958969','#c0aa83','#9c8c74'][p.id%4]);
 line([{x:at.x-5*k,y:at.y-14*k+up},{x:at.x-8*k,y:at.y-8*k+up+swing}], '#bc9775',3*k);line([{x:at.x+5*k,y:at.y-14*k+up},{x:at.x+8*k,y:at.y-9*k+up-swing}], '#bc9775',3*k);
 ellipse(at.x,at.y-21*k+up,4.5*k,5*k,['#c4a180','#9f795a','#b98f69'][p.id%3]);if(p.job!=='idle'){ellipse(at.x,at.y-25*k+up,p.job==='farm'?8*k:6*k,2*k,hatColor(p.job));polygon([{x:at.x-5*k,y:at.y-25*k+up},{x:at.x-2*k,y:at.y-30*k+up},{x:at.x+5*k,y:at.y-25*k+up}],hatColor(p.job));}
 if(p.load>0){if(p.loadKind==='wood')woodpile({x:at.x+6*k,y:at.y-9*k},6);else basket({x:at.x+6*k,y:at.y-9*k},10);}
 if(p.phase==='work'&&p.job==='wood'){line([{x:at.x+7*k,y:at.y-10*k},{x:at.x+12*k+swing,y:at.y-24*k}],'#ad8c5b',2*k);rock({x:at.x+13*k+swing,y:at.y-23*k},.35*k);}
 if(sel){ctx.font=Math.max(11,11*k)+'px system-ui';ctx.textAlign='center';ctx.fillStyle='#f0edd5';ctx.fillText(p.name,at.x,at.y-37*k);}}
function building(b){const p=iso(b.x,b.y),k=sx/20,ghost=!b.done;ctx.globalAlpha=ghost?.42:1;
 diamond(b.x,b.y,b.kind==='field'?'#746440':'#736f4c44',ghost?'#cfdeb1':'#263e2855');
 if(['fence','wall','gate'].includes(b.kind)){if(b.kind==='wall'){for(let i=0;i<3;i++)rock({x:p.x+(i-1)*7*k,y:p.y+(i-1)*3*k},.55*k);}else{for(const d of [-.45,.45]){const a=iso(b.x+d,b.y);line([{x:a.x,y:a.y},{x:a.x,y:a.y-17*k}],'#c0a076',3*k);}const a=iso(b.x-.45,b.y),c=iso(b.x+.45,b.y);for(const yy of [6,13])line([{x:a.x,y:a.y-yy*k},{x:c.x,y:c.y-yy*k}],b.kind==='gate'?'#e0c18d':'#a8895e',2*k);if(b.kind==='gate')line([{x:a.x,y:a.y-6*k},{x:c.x,y:c.y-13*k}],'#e0c18d',2*k);}}
 else if(b.kind==='field'){for(let i=0;i<4;i++){const a=iso(b.x-.4+i*.22,b.y-.4),c=iso(b.x-.4+i*.22,b.y+.4);line([a,c],'#453c2b',1.5);if(b.growth>10)for(let j=0;j<4;j++){const t=iso(b.x-.4+i*.22,b.y-.4+j*.22);line([t,{x:t.x,y:t.y-(3+b.growth*.06)*k}],b.growth>80?'#e1c078':'#b4bb68',2*k);}}if(b.plowed){line([iso(b.x-.4,b.y),iso(b.x+.4,b.y)],'#d9ba75',2);}}
 else if(b.kind==='road'){for(let j=0;j<5;j++)rock(iso(b.x+(j-2)*.18,b.y),.3*k);}
 else if(b.kind==='rack'){for(const dx of [-9,9])line([{x:p.x+dx*k,y:p.y},{x:p.x+dx*k,y:p.y-23*k}],'#aa8960',3*k);line([{x:p.x-11*k,y:p.y-21*k},{x:p.x+11*k,y:p.y-21*k}],'#b5996b',3*k);for(let j=0;j<3;j++)line([{x:p.x+(j-1)*6*k,y:p.y-19*k},{x:p.x+(j-1)*6*k,y:p.y-10*k}],'#a96f4e',4*k);}
 else if(b.kind==='plow'){line([{x:p.x-12*k,y:p.y},{x:p.x+12*k,y:p.y-9*k}],'#d1ad75',3*k);line([{x:p.x-5*k,y:p.y-2*k},{x:p.x-11*k,y:p.y-18*k}],'#b08b58',3*k);}
 else {const roof=b.kind==='store'?'#b79860':b.kind==='pen'?'#8d7756':'#a89062';polygon([{x:p.x-17*k,y:p.y},{x:p.x+9*k,y:p.y+9*k},{x:p.x+18*k,y:p.y},{x:p.x-8*k,y:p.y-9*k}], '#66563e');polygon([{x:p.x-17*k,y:p.y},{x:p.x-4*k,y:p.y-29*k},{x:p.x+9*k,y:p.y+9*k}],roof,'#67533c');polygon([{x:p.x-4*k,y:p.y-29*k},{x:p.x+9*k,y:p.y+9*k},{x:p.x+18*k,y:p.y},{x:p.x+5*k,y:p.y-37*k}], '#7d6e48','#584c34');polygon([{x:p.x-7*k,y:p.y+2*k},{x:p.x-4*k,y:p.y-11*k},{x:p.x+2*k,y:p.y+5*k}],'#302d20');if(b.kind==='store')basket({x:p.x+12*k,y:p.y+6*k},35);}
 ctx.globalAlpha=1;if(ghost){ctx.fillStyle='#1d3025';ctx.fillRect(p.x-12*k,p.y+9*k,24*k,3*k);ctx.fillStyle='#d3dca8';ctx.fillRect(p.x-12*k,p.y+9*k,24*k*Math.min(1,b.work/BUILD[b.kind].work),3*k);}}
function animal(p,k){ellipse(p.x,p.y-9*k,12*k,7*k,'#9b8564');for(const x of [-7,7])line([{x:p.x+x*k,y:p.y-7*k},{x:p.x+x*k,y:p.y+2*k}],'#534d3b',3*k);ellipse(p.x+12*k,p.y-12*k,5*k,6*k,'#a28b67');line([{x:p.x+9*k,y:p.y-16*k},{x:p.x+8*k,y:p.y-22*k}],'#d5c6a0',2*k);line([{x:p.x+15*k,y:p.y-16*k},{x:p.x+18*k,y:p.y-20*k}],'#d5c6a0',2*k);}
function drawLocal(time){coordinates();const t=game.tile;const edge=[iso(-.5,-.5),iso(18.5,-.5),iso(18.5,18.5),iso(-.5,18.5)];polygon(edge.map(p=>({x:p.x,y:p.y+13*sx/20})),'#1b3024');polygon(edge,'#586747');
 for(let x=0;x<19;x++)for(let y=0;y<19;y++){const n=(Math.sin(x*82+y*19+t.q*31)*43758)%1;diamond(x,y,t.type==='mountain'?(n>.2?'#7d8269':'#737b61'):t.type==='meadow'?(n>.2?'#7e8a50':'#76834d'):(n>.2?'#596d47':'#526543'),buildMode?'#ffffff0c':null);if(x===9||y===9)diamond(x,y,'#a18f6040');}
 // Spring and small stream, always available for recovery work.
 for(let x=0;x<5;x++)diamond(x,9,'#73988b');for(let x=0;x<5;x++){const p=iso(x,9);line([{x:p.x-4,y:p.y},{x:p.x+6,y:p.y+2}],'#bbd7bd66',1);}
 const draws=[];for(const n of t.nodes){if(n.kind==='water')continue;draws.push({depth:n.x+n.y,run:()=>{const p=iso(n.x,n.y),k=sx/20;if(n.amount<=0){if(n.kind==='wood'){ellipse(p.x,p.y,3*k,2*k,'#c5a371');}return;}if(n.kind==='wood')tree(p,n);if(n.kind==='stone')rock(p,.6*k);if(n.kind==='food'){ellipse(p.x,p.y-4*k,9*k,6*k,'#708047');for(let i=0;i<4;i++)ellipse(p.x+(i%2*7-4)*k,p.y-(4+Math.floor(i/2)*4)*k,1.7*k,1.7*k,'#c2a079');}if(n.kind==='fiber'){for(let i=0;i<4;i++)line([{x:p.x,y:p.y},{x:p.x+(i-1.5)*4*k,y:p.y-(8+i%2*4)*k}],'#c1bb7c',1.5*k);}}});}
 for(const b of t.buildings)draws.push({depth:b.x+b.y+.2,run:()=>building(b)});
 const fire=iso(9,9);const glow=ctx.createRadialGradient(fire.x,fire.y,1,fire.x,fire.y,65);glow.addColorStop(0,'#ffcf7430');glow.addColorStop(1,'#ffd57500');ctx.fillStyle=glow;ctx.fillRect(fire.x-70,fire.y-70,140,140);
 draws.push({depth:18,run:()=>flame(fire,time,t.stock.wood<=0)});draws.push({depth:19,run:()=>woodpile(iso(11,8),t.stock.wood)});draws.push({depth:18.5,run:()=>basket(iso(8,10),t.stock.food)});draws.push({depth:17,run:()=>basket(iso(7,10),t.stock.water,'#8d9b8d')});draws.push({depth:19,run:()=>{for(let j=0;j<Math.min(8,Math.ceil(t.stock.stone/8));j++)rock(iso(12+(j%2)*.25,7+Math.floor(j/2)*.15),.35*sx/20);}});
 for(const p of game.people())draws.push({depth:p.x+p.y+.5,run:()=>villager(p,time)});
 const pen=t.buildings.find(b=>b.kind==='pen'&&b.done);if(pen)for(let i=0;i<t.herd;i++)draws.push({depth:pen.x+pen.y+1+i*.2,run:()=>animal(iso(pen.x+.6,pen.y+.3+i*.6),sx/20*.7)});
 draws.sort((a,b)=>a.depth-b.depth).forEach(d=>d.run());
 if(drag?.type==='box'){ctx.strokeStyle='#dfedb5';ctx.lineWidth=1;ctx.fillStyle='#d8eba91a';ctx.fillRect(drag.start.x,drag.start.y,drag.now.x-drag.start.x,drag.now.y-drag.start.y);ctx.strokeRect(drag.start.x,drag.start.y,drag.now.x-drag.start.x,drag.now.y-drag.start.y);}
 if(drag?.type==='villager'){ellipse(drag.now.x,drag.now.y,12,5,'#e3e9b577');}
 if(drag?.type==='build'){const a=cell(drag.now);if(a.x>=0&&a.y>=0&&a.x<19&&a.y<19)diamond(a.x,a.y,'#e9eab345','#eff9be');}
}
function drawMap(){mapPoints=[];const radius=Math.min(w/17,h/16)*zoom,cx=w*.5+pan.x,cy=h*.55+pan.y;
 for(const t of Object.values(game.s.tiles)){const p={x:cx+radius*Math.sqrt(3)*(t.q+t.r/2),y:cy+radius*1.5*t.r};mapPoints.push({t,p,radius});const corners=Array.from({length:6},(_,i)=>({x:p.x+Math.cos((i*60-30)*Math.PI/180)*(radius-2),y:p.y+Math.sin((i*60-30)*Math.PI/180)*(radius-2)}));polygon(corners,t.seen?{mountain:'#7d856d',woodland:'#536c49',rocky:'#68755a',river:'#668776',meadow:'#8e9959'}[t.type]:'#233d30',t.id===game.s.location?'#f5d39c':t.visited?'#aabd8666':'#182e23',t.id===game.s.location?2.5:1);
 if(!t.seen)continue;if(t.elevation){polygon([{x:p.x-radius*.65,y:p.y+radius*.3},{x:p.x-radius*.05,y:p.y-radius*.65},{x:p.x+radius*.58,y:p.y+radius*.3}],'#b4b99b','#576850');polygon([{x:p.x-radius*.05,y:p.y-radius*.65},{x:p.x+radius*.58,y:p.y+radius*.3},{x:p.x+radius*.07,y:p.y+radius*.17}],'#929d80');}
 else if(t.type==='woodland'){for(let j=0;j<3;j++)polygon([{x:p.x+(j-1)*radius*.45,y:p.y-radius*.4},{x:p.x+(j-1)*radius*.45+radius*.22,y:p.y+radius*.2},{x:p.x+(j-1)*radius*.45-radius*.22,y:p.y+radius*.2}],'#294d32');}
 else if(t.type==='river'||t.type==='meadow')line([{x:p.x-radius*.55,y:p.y-radius*.5},{x:p.x-radius*.08,y:p.y},{x:p.x+radius*.1,y:p.y+radius*.5}],'#b1c6a5',3);
 const residents=game.people(t).length;if(residents){ellipse(p.x,p.y+radius*.38,5,3,'#f1bd76');ctx.fillStyle='#f0ebd6';ctx.font='11px system-ui';ctx.textAlign='center';ctx.fillText(String(residents),p.x,p.y+radius*.8);}if(t.road){ctx.strokeStyle='#e4ca97';ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,radius*.7,0,Math.PI);ctx.stroke();}
 }
 ctx.textAlign='right';ctx.font='12px system-ui';ctx.fillStyle='#d4dfbb';ctx.fillText('N ↑',w-22,h-50);
}
function draw(now){ctx.clearRect(0,0,w,h);if(map)drawMap();else drawLocal(now/1000);if(practice){const elapsed=(now-practice.start)/1000;practice.position=(Math.sin(elapsed*practice.speed)+1)/2;const needle=$('needle');if(needle)needle.style.left=practice.position*100+'%';}}
function icon(job){const c=hatColor(job);return '<svg width="28" height="36" viewBox="0 0 28 36" aria-hidden="true"><path d="M8 34V24h12v10M6 26l2-12h12l2 12" fill="#b8a17c"/><ellipse cx="14" cy="10" rx="6" ry="7" fill="#bf9871"/><path d="M5 8h19L17 1 7 5z" fill="'+c+'"/></svg>';}
function renderUI(){const t=game.tile,s=game.s;selected=new Set([...selected].filter(id=>game.people().some(p=>p.id===id)));
 $('resources').innerHTML=RESOURCE.map(k=>'<div class="resource '+(t.stock[k]<5?'low':'')+'"><label>'+k[0].toUpperCase()+k.slice(1)+'</label><strong>'+fmt(t.stock[k])+'</strong><small>/ '+game.cap()+'</small></div>').join('');
 $('location-label').textContent=map?'THE KNOWN LAND':t.name.toUpperCase();$('scene-title').textContent=map?'Follow your curiosity.':s.complete?'Tonight, the hearth stays.':t.type==='mountain'?'A pause among the stones.':'A place for the ember.';
 $('scene-detail').textContent=map?(t.elevation?'High ground reveals two hexes, unless a ridge intervenes.':'You can see the neighboring land.'):(s.migration?'The elders are ready to move.':t.stock.wood<=0?'The ember waits for another load.':'The hearth is warm.');
 $('clock').textContent='Day '+(1+Math.floor(s.time/180));$('map-toggle').textContent=map?'Return to the hearth':'Explore the land';$('pause').innerHTML=paused?'▶ <span>Resume</span>':'Ⅱ <span>Pause</span>';$('pause').setAttribute('aria-label',paused?'Resume game':'Pause game');$('pause-label').hidden=!paused;$('step').disabled=!paused||modalPause;
 $('people-count').textContent=game.people().length;$('people').innerHTML=game.people().map(p=>'<button class="person '+(selected.has(p.id)?'selected':'')+'" data-person="'+p.id+'" aria-pressed="'+selected.has(p.id)+'" title="'+esc(p.blocked||JOBS[p.job])+'">'+icon(p.job)+'<span><strong>'+p.name+'</strong><small>'+esc(p.blocked?'Taking a pause':JOBS[p.job])+'</small></span></button>').join('');
 $('readiness').textContent=game.ready()+'%';$('readiness-bar').value=game.ready();$('knowledge').textContent=fmt(s.knowledge)+' understanding';const next=Object.entries(TECH).find(([id,d])=>!game.has(id)&&d.needs.every(n=>game.has(n)));$('next-practice').textContent=next?next[1].name+' · '+next[1].knowledge+' understanding':s.complete?'You made a place to return to.':'Bring the pieces together for the first furrow.';
 if(s.events.length)say(s.events.at(-1));renderPanel();if(s.complete&&!lastComplete){lastComplete=true;finish();}
}
function renderPanel(){let html='';if(tab==='work'){
 html='<p class="small-text">'+selected.size+' selected. Tap a task below, or a resource in the landscape.</p><div class="control-stack">'+['wood','food','water','stone','fiber','build',...(game.has('cultivation')?['farm']:[]),...(game.has('husbandry')?['herd']:[]),...(game.has('plow')?['plow']:[])].map(k=>'<button data-job="'+k+'">'+JOBS[k]+'</button>').join('')+'</div><p class="panel-label">LEARN BY DOING</p><div class="practice-grid"><button data-practice="knap">Shape flint</button><button data-practice="hunt">Hunt</button><button data-practice="gather">Gather</button></div><p class="small-text">Practice is optional. Assigned work also builds understanding.</p><button id="protect-mode" aria-pressed="'+protectMode+'">'+(protectMode?'Finish protecting':'Protect individual trees')+'</button>';
 if(game.has('woodland'))html+='<label class="check-row"><input id="mature-policy" type="checkbox" '+(game.s.policies.mature?'checked':'')+'>Harvest mature trees only</label>';
 if(game.has('routes'))html+='<p class="panel-label">BEYOND THIS HEARTH</p><button id="route-button">Send a gathering party</button>';
 if(game.has('sledges'))html+='<button id="road-button" '+(game.tile.road?'disabled':'')+'>'+ (game.tile.road?'Route improved':'Improve this route')+'</button><p class="small-text">22 stone · 14 wood · 12 food</p>';
 for(const r of game.s.routes)html+='<div class="list-row"><span>'+r.people.length+' gathering '+r.kind+'</span><button data-recall="'+r.id+'">Recall</button></div>';
 }else if(tab==='build'){
 html='<p class="small-text">Place an outline, then assign builders. Drag to lay a fence. Tap a completed structure to move or dismantle it.</p><div class="control-stack">'+Object.entries(BUILD).filter(([id,b])=>b.needs.every(n=>game.has(n))).map(([id,b])=>'<button data-build="'+id+'" aria-pressed="'+(buildMode===id)+'">'+b.name+'<small>'+game.quote(b.cost)+'</small></button>').join('')+'</div>'+(buildMode?'<button id="cancel-build">Finish placing</button>':'');
 }else{
 html=Object.entries(TECH).filter(([id,d])=>!game.has(id)&&d.needs.every(n=>game.has(n))).map(([id,d])=>'<div class="tech"><strong>'+d.name+'</strong><p>'+d.text+'</p><small>'+d.knowledge+' understanding · '+game.quote(d.cost)+'</small><button data-learn="'+id+'" '+(game.s.knowledge<d.knowledge||Object.entries(d.cost).some(([k,v])=>game.tile.stock[k]<v)?'disabled':'')+'>Learn this practice</button></div>').join('');html+='<p class="panel-label">SHARED KNOWLEDGE</p><p class="small-text">'+(game.s.tech.map(k=>TECH[k].name).join(' · ')||'The tribe learns through its work.')+'</p>';
 }$('panel').innerHTML=html;
}
function assign(kind,target){if(!selected.size){say('Select one or more villagers first.');return;}if(!game.assign([...selected],kind,target))say('Learn this practice first.');else{say(selected.size+' assigned to '+JOBS[kind].toLowerCase()+'.');game.message(selected.size+' assigned to '+JOBS[kind].toLowerCase()+'.');}buildMode=null;moveId=null;renderUI();save();}
function personAt(p){return game.people().filter(v=>{const a=iso(v.x,v.y);return Math.hypot(p.x-a.x,p.y-(a.y-12*sx/20))<Math.max(15,14*sx/20);}).sort((a,b)=>b.x+b.y-a.x-a.y)[0];}
function select(id,add){if(!add)selected.clear();if(add&&selected.has(id))selected.delete(id);else selected.add(id);renderUI();}
function targetAt(p){const c=cell(p),t=game.tile;const nodes=t.nodes.filter(n=>{const a=iso(n.x,n.y),height=n.kind==='wood'&&n.amount>0?(15+n.age*32)*sx/20:5;return Math.abs(p.x-a.x)<Math.max(sx*.65,12)&&p.y>a.y-height&&p.y<a.y+sy;}).sort((a,b)=>b.x+b.y-a.x-a.y);const b=t.buildings.find(b=>b.x===c.x&&b.y===c.y);return{c,node:nodes[0],building:b};}
function clickWorld(p,force=false){if(map){const a=mapPoints.find(a=>Math.hypot(p.x-a.p.x,p.y-a.p.y)<a.radius*.9);if(a?.t.seen)travel(a.t);return;}
 const at=targetAt(p);if(moveId){const err=game.movePlan(moveId,at.c.x,at.c.y);say(err||'Outline relocated.');if(!err)moveId=null;renderUI();save();return;}
 if(buildMode){const err=game.place(buildMode,at.c.x,at.c.y);say(err||'Outline placed. Assign builders to bring it to life.');save();return;}
 if(protectMode&&at.node?.kind==='wood'){at.node.protected=!at.node.protected;say(at.node.protected?'This tree will be left standing.':'This tree is available for harvest.');save();return;}
 const person=personAt(p);if(person&&!force){select(person.id,false);return;}
 if(at.building){if(force)assign(at.building.done?at.building.kind==='field'?'farm':at.building.kind==='pen'?'herd':'build':'build',at.building.id);else inspectBuilding(at.building);return;}
 if(at.node)assign(at.node.kind,at.node.id);
}
function point(e){const rect=canvas.getBoundingClientRect();return{x:e.clientX-rect.left,y:e.clientY-rect.top};}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(modalPause)return;const p=point(e);pointers.set(e.pointerId,p);canvas.setPointerCapture(e.pointerId);if(pointers.size===2){const a=[...pointers.values()];drag={type:'pinch',length:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),zoom};return;}if(e.button===2){clickWorld(p,true);return;}
 const person=!map&&personAt(p);if(person){if(!selected.has(person.id))select(person.id,e.shiftKey);drag={type:'villager',start:p,now:p};}
 else if(e.button===1||e.altKey||map)drag={type:'pan',start:p,now:p,pan:{...pan}};
 else if(buildMode)drag={type:'build',start:p,now:p,last:null};else drag={type:'box',start:p,now:p,add:e.shiftKey};});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(pointers.has(e.pointerId))pointers.set(e.pointerId,p);if(!drag)return;
 if(drag.type==='pinch'){const a=[...pointers.values()];if(a.length===2)zoom=Math.min(2.5,Math.max(.6,drag.zoom*Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)/Math.max(1,drag.length)));return;}drag.now=p;
 if(drag.type==='pan'){pan.x=drag.pan.x+p.x-drag.start.x;pan.y=drag.pan.y+p.y-drag.start.y;}
 if(drag.type==='build'&&['fence','wall','gate'].includes(buildMode)){const c=cell(p),k=c.x+','+c.y;if(drag.last!==k){game.place(buildMode,c.x,c.y);drag.last=k;}}
});
canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);const d=drag;drag=null;if(!d||d.type==='pinch')return;const p=point(e),moved=Math.hypot(p.x-d.start.x,p.y-d.start.y)>8;
 if(d.type==='box'&&moved){if(!d.add)selected.clear();for(const v of game.people()){const a=iso(v.x,v.y);if(a.x>=Math.min(p.x,d.start.x)&&a.x<=Math.max(p.x,d.start.x)&&a.y>=Math.min(p.y,d.start.y)&&a.y<=Math.max(p.y,d.start.y))selected.add(v.id);}renderUI();}
 else if(d.type==='villager'&&moved)clickWorld(p,true);else if(!moved)clickWorld(p);save();});
canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);drag=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.min(2.5,Math.max(.6,zoom*(e.deltaY<0?1.08:.92)));},{passive:false});
$('people').addEventListener('click',e=>{const b=e.target.closest('[data-person]');if(b)select(Number(b.dataset.person),true);});
$('select-all').onclick=()=>{selected=new Set(game.people().map(p=>p.id));renderUI();};$('rest').onclick=()=>assign('idle');
$('pause').onclick=()=>{paused=!paused;renderUI();};$('step').onclick=()=>{if(paused&&!modalPause){game.tick(1);renderUI();save();}};
$('map-toggle').onclick=()=>{map=!map;zoom=1;pan={x:0,y:0};buildMode=null;renderUI();};$('center').onclick=()=>{zoom=1;pan={x:0,y:0};};$('zoom-in').onclick=()=>zoom=Math.min(2.5,zoom*1.2);$('zoom-out').onclick=()=>zoom=Math.max(.6,zoom/1.2);
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{tab=b.dataset.tab;for(const a of document.querySelectorAll('[data-tab]'))a.setAttribute('aria-selected',String(a===b));$('panel').setAttribute('aria-labelledby',b.id);buildMode=null;renderPanel();};
$('panel').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.job)assign(b.dataset.job);if(b.dataset.build){buildMode=buildMode===b.dataset.build?null:b.dataset.build;protectMode=false;map=false;renderUI();$('hint').textContent=buildMode?'Place '+BUILD[buildMode].name.toLowerCase()+' outlines. Escape finishes placement.':'Select a villager, then tap a resource.';}if(b.dataset.learn){if(game.learn(b.dataset.learn)){save();renderUI();}}if(b.dataset.practice)startPractice(b.dataset.practice);if(b.id==='cancel-build'){buildMode=null;renderPanel();}if(b.id==='protect-mode'){protectMode=!protectMode;buildMode=null;renderPanel();}if(b.id==='route-button')routeDialog();if(b.dataset.recall){game.recall(b.dataset.recall);save();renderUI();}if(b.id==='road-button'){say(game.road()?'Road outline placed. Assign builders.':'A road is already planned, or this path needs room.');save();renderUI();}});
$('panel').addEventListener('change',e=>{if(e.target.id==='mature-policy'){game.s.policies.mature=e.target.checked;save();}});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON','A'].includes(e.target.tagName)||modalPause)return;if(e.code==='Space'){e.preventDefault();paused=!paused;renderUI();}if(e.key==='Escape'){buildMode=null;protectMode=false;moveId=null;selected.clear();renderUI();}if(e.key.toLowerCase()==='m')$('map-toggle').click();});
function inspectBuilding(b){modal('YOUR CAMP',BUILD[b.kind].name,'<p>'+(b.done?'Built and in use.':'An outline waiting for workers and materials.')+'</p><p>'+game.quote(BUILD[b.kind].cost)+'</p><div class="modal-buttons"><button id="assign-building" class="primary">Assign selected villagers</button>'+(!b.done?'<button id="move-building">Move outline</button>':'')+'<button id="remove-building">'+(b.done?'Dismantle · recover 65% of materials':'Cancel outline · recover delivered materials')+'</button></div>');$('assign-building').onclick=()=>{close();assign(b.done?b.kind==='field'?'farm':b.kind==='pen'?'herd':'build':'build',b.id);};if($('move-building'))$('move-building').onclick=()=>{moveId=b.id;close();say('Tap the new location for this outline.');};$('remove-building').onclick=()=>{game.remove(b.id);close();save();renderUI();};}
function travel(t){if(t.id===game.s.location){map=false;renderUI();return;}const adjacent=distance(game.tile,t)===1;modal(t.visited?'A FAMILIAR PLACE':'BEYOND THE HEARTH',t.name,'<p>'+({mountain:'Rocky ground rises into a pass. Carrying enough provisions will take preparation.',woodland:'Trees and sheltered ground. What could another visit make possible?',rocky:'Stone lies close to the surface. A useful place to gather building material.',river:'A ribbon of water runs through sheltered ground.',meadow:'Open grassland and running water. There is room to grow here.'}[t.type])+'</p>'+(!adjacent?'<p>Travel through a neighboring hex to get here.</p>':'<div id="travel-quote"></div>'+(game.has('settlement')?'<label class="check-row">Leave residents <select id="leave">'+Array.from({length:game.people().length},(_,i)=>'<option value="'+i+'">'+i+'</option>').join('')+'</select></label>':'')+'<button id="travel-confirm" class="primary">Carry the ember here</button>'));
 if(!adjacent)return;const update=()=>{const q=game.travelQuote(t.id,Number($('leave')?.value||0));$('travel-quote').innerHTML='<p>'+(q.cost&&Object.keys(q.cost).length?'Expedition: '+game.quote(q.cost):'An ordinary migration is always possible without a provision fee.')+'</p><p>'+esc(q.reason)+'</p>';$('travel-confirm').disabled=!q.ok;};update();if($('leave'))$('leave').onchange=update;$('travel-confirm').onclick=()=>{const err=game.migrate(t.id,Number($('leave')?.value||0));if(err){say(err);return;}selected.clear();map=false;zoom=1;pan={x:0,y:0};paused=false;close();save();renderUI();};}
function routeDialog(){const targets=game.neighbors().filter(t=>t.visited);modal('THERE AND BACK','Pack a gathering party.','<p>Use your selected villagers. Leave at least one person at the hearth. Each worker takes 4 food and 3 water for the first trip; repeating trips use 3 food and 2 water.</p><p>Parties return when the destination needs rest or their provisions run out.</p><label class="check-row">Destination <select id="route-to">'+targets.map(t=>'<option value="'+t.id+'">'+t.name+' ('+t.id+')</option>').join('')+'</select></label><label class="check-row">Gather <select id="route-kind">'+['wood','food','stone','fiber','water'].map(k=>'<option>'+k+'</option>').join('')+'</select></label><p id="route-status" role="status"></p><button id="dispatch" class="primary" '+(!targets.length?'disabled':'')+'>Send '+selected.size+' selected villagers</button>');$('dispatch').onclick=()=>{const err=game.dispatch([...selected],$('route-to').value,$('route-kind').value);if(err){$('route-status').textContent=err;return;}close();save();renderUI();};}
function startPractice(kind){if(game.s.time-game.s.practiceAt<35){modal('A LITTLE PATIENCE','Let the lesson settle.','<p>Return to the camp for a little while. Your people keep learning through their work.</p>');return;}const skill=game.s.skills[kind],width=Math.min(.65,.18+skill*.035),titles={knap:'Find the useful edge.',hunt:'Read the movement.',gather:'Learn what to keep.'},instructions={knap:'Choose the strike when the marker reaches the pale band. Even an imperfect flake teaches something.',hunt:'Choose the moment to approach. The hunt is represented without combat or graphic imagery.',gather:'Recognize a useful plant when the marker reaches the pale band. Bring back fibers and seed.'};modal('LEARN BY DOING',titles[kind],'<p>'+instructions[kind]+'</p><div class="practice-track"><div class="practice-target" style="left:'+((.5-width/2)*100)+'%;width:'+(width*100)+'%"></div><div id="needle" class="practice-needle"></div></div><button id="practice-act" class="primary">'+(kind==='knap'?'Strike':kind==='hunt'?'Approach':'Gather')+'</button><p class="small-text">Practice '+(skill+1)+'. Time at camp is paused. Experience widens the useful band.</p>');practice={kind,width,start:performance.now(),position:.5,speed:Math.max(.8,2.1-skill*.08)};$('practice-act').onclick=()=>{const pr=practice,quality=Math.max(.2,1-Math.abs(pr.position-.5)/(pr.width+.15));practice=null;game.practice(kind,quality);for(let i=0;i<8;i++)game.tick(1);modal('A SHARED LESSON',quality>.7?'That felt familiar.':'Something useful to remember.','<p>The tribe gained understanding and useful material. Ordinary assigned work keeps building knowledge, too.</p><button id="practice-done" class="primary">Return to the hearth</button>');$('practice-done').onclick=()=>{close();renderUI();};save();};}
function finish(){modal('STAGE 01 COMPLETE','The first furrow.','<p>The team finishes its work. The stores hold enough for tonight. People return to the hearth, and this time it can stay.</p><div class="stats"><div>Journey time<strong>'+clock(game.s.time)+'</strong></div><div>Places visited<strong>'+game.s.visits.length+'</strong></div></div><p>Stage 2 will expand this community into an agricultural age. That stage is not built yet. You can keep tending this world or begin another journey with inherited traditions.</p><div class="modal-buttons"><button id="linger" class="primary">Stay by the fire</button><button id="new-journey">Carry knowledge into a new journey</button></div>');$('linger').onclick=close;$('new-journey').onclick=prestigeDialog;}
function prestigeDialog(){modal('PASS IT ON','Carry the knowledge onward?','<p>Your completed world will be preserved in Journey. A fresh journey begins with new supplies, a small tribe, and '+Math.min(5,game.s.traditions+1)+' inherited traditions. Each tradition improves work and learning by 8%, up to five traditions.</p><p>The new journey resets its map, buildings, discoveries, and resources. You can revisit the completed world.</p><button id="confirm-prestige" class="primary">Preserve this world and begin again</button>');$('confirm-prestige').onclick=async()=>{try{const old=game.serialize(),raw=await platform.load(ARCHIVE),archives=raw?JSON.parse(raw):[];if(!Array.isArray(archives))throw Error();archives.push(old);await platform.save(ARCHIVE,JSON.stringify(archives));game.prestige();lastComplete=false;selected=new Set([0]);close();save();renderUI();}catch(e){say('Could not preserve this world. Export a backup; your journey has not been reset.');close();}};}
async function settings(){modal('YOUR JOURNEY','A moment by the fire.','<p>This journey is saved on this device. Export it to move between browsers or keep a backup. Hidden tabs and closed apps do not consume supplies.</p><div class="stats"><div>Journey<strong>'+clock(game.s.time)+'</strong></div><div>Traditions<strong>'+game.s.traditions+' / 5</strong></div></div><div class="modal-buttons"><button id="export">Export journey</button><button id="import">Import journey</button><button id="archives">Visit a completed world</button>'+(game.s.complete?'<button id="prestige">Begin another journey</button>':'')+'<button id="instructions">How to play</button><a href="index.html">Return to Stage 0 · The Cave</a></div><label class="check-row"><input type="checkbox" id="motion" '+(reduced?'checked':'')+'>Quiet motion</label>');$('export').onclick=async()=>{const raw=saveBlocked?await platform.load(KEY):game.serialize();await platform.download('singularity-clicker-hearth.json',raw||game.serialize());};$('import').onclick=()=>$('import-file').click();$('archives').onclick=archiveDialog;if($('prestige'))$('prestige').onclick=prestigeDialog;$('motion').onchange=e=>reduced=e.target.checked;$('instructions').onclick=help;}
function help(){modal('THE HEARTH','Give the work a direction.','<ul class="help-list"><li>Select villagers below the landscape. Tap a resource or choose a job to assign them. Mouse users can box-select and right-click, or drag a villager onto work.</li><li>Workers gather, haul, deposit, and repeat. They rest when an area is depleted or storage is full.</li><li>The hearth uses wood automatically. Keep some woodcutters working and food and water coming home.</li><li>Build places outlines; builders bring materials and finish them.</li><li>Explore neighboring hexes. High ground reveals up to two hexes, unless a ridge blocks the view.</li><li>Keep learning through work and optional practice. The final goal is a working plow.</li><li>No one starves or dies. The elders suggest migration when supplies stay empty.</li><li>Space pauses. M opens the map. Scroll or pinch to zoom; drag the map or Alt-drag the camp to pan.</li></ul><button id="help-done" class="primary">Back to the fire</button>');$('help-done').onclick=close;}
async function archiveDialog(){let archives=[];try{archives=JSON.parse(await platform.load(ARCHIVE)||'[]');}catch(e){}modal('REMEMBERED PLACES','Completed worlds.','<p>Opening a world replaces the active journey. Export your current journey first if you want to keep it.</p><div class="modal-buttons">'+archives.map((a,i)=>'<button data-archive="'+i+'">Completed world '+(i+1)+'</button>').join('')+'</div>'+(!archives.length?'<p>No completed worlds have been archived yet.</p>':''));for(const b of document.querySelectorAll('[data-archive]'))b.onclick=()=>confirmImport(new Hearth(JSON.parse(archives[Number(b.dataset.archive)])));}
function confirmImport(incoming){modal('RESTORE A JOURNEY','Replace the active journey?','<p>This replaces the current Stage 1 journey with the selected save. Stage 0 is unaffected.</p><button id="confirm-import" class="primary">Restore this journey</button>');$('confirm-import').onclick=()=>{game=incoming;saveBlocked=false;lastComplete=game.s.complete;selected.clear();close();save();renderUI();};}
$('import-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>5e6)throw Error();confirmImport(new Hearth(JSON.parse(await f.text())));}catch(e){modal('SAVE UNCHANGED','This journey could not be opened.','<p>Choose a compatible Hearth JSON export. Your existing journey has not been replaced.</p>');}};
$('settings').onclick=settings;document.addEventListener('visibilitychange',()=>{last=performance.now();acc=0;if(document.hidden)save();});window.addEventListener('pagehide',save);window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue!==lastSerialized){saveBlocked=true;paused=true;modal('JOURNEY UPDATED','Another window has this journey.','<p>Reload this page to continue from the other window without overwriting its progress.</p>');}});
function frame(now){const dt=Math.min(.25,(now-last)/1000);last=now;if(loaded&&!paused&&!modalPause&&!document.hidden&&!saveBlocked){acc+=dt;while(acc>=1){game.tick(1);acc--;if(game.s.migration){paused=true;break;}}saveTime+=dt;uiTime+=dt;if(saveTime>5){save();saveTime=0;}if(uiTime>.8){renderUI();uiTime=0;}}
 draw(now);requestAnimationFrame(frame);}
load();resize();requestAnimationFrame(frame);
})();
